version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-docker
    ports:
      - 8080:80
    volumes:
    #- ./public/api:/var/www/html/
    - ./gallery/api:/var/www/html/